### ISSUE TITLE
500 error with redmine 3.4.2 when clicking existing issue

### ISSUE THREAD

**Issue by SperlingR** [jrupesh/event_notifications#35]
Hi,
after updating redmine from 3.3.3 to 3.4.2 we get this error when clicking on an existing error.
Our installation is based on the latest bitnami stack (Redmine V3.3.3 updated to V3.4.2).
At the old installation (V3.3.3) the plugin runs next to several plugins without failure.
The error is independend from other plugins (for testing we only installed this plugin => error occurs)

Production log says "ActionView::Template::Error (undefined method `render_custom_fields_rows'"

Any ideas on how we can fix it are highly appreciated.

Here is the part from production.log:
~~~
Started GET "/redmine/issues/4559" for 192.168.0.1 at 2017-07-31 17:03:06 +0200
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"4559"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (9.8ms)
  Rendered plugins/event_notifications/app/views/issues/show.html.erb within layouts/base (176.8ms)
Completed 500 Internal Server Error in 525ms (ActiveRecord: 91.6ms)

ActionView::Template::Error (undefined method `render_custom_fields_rows' for #<#<Class:0x0055e7a98425$
Did you mean?  render_custom_fields_tabs
               render_custom_field_values):
    68:     end
    69:   end
    70: end %>
    71: <%= render_custom_fields_rows(@issue) %>
    72: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    73: </div>
    74:
  plugins/event_notifications/app/views/issues/show.html.erb:71:in `_plugins_event_notifications_app_v$
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
~~~

**Comment by mdima** [comment]
Same issue here using Redmine 3.4.2.stable. 

Thanks,
Michele

**Comment by seb368** [comment]
Same issue here, same constellation. 

Thanks for fixing the problem.

**Comment by GrimDReaper** [comment]
This problem with view is not one. Additional problem is witch saving settings of plugin. On redmine 3.4.x are some changes, that can old plugins paralized. 

Is this plugin still developed?

**Comment by shenergetix** [comment]
Hey jrupesh,
same issue here using Redmine 3.4.3 stable. Are you developing the plugin futher? Thanks for a quick reaction.

**Comment by jrupesh** [comment]
Issue corrected with latest commit.
Thanks.

**Comment by mdima** [comment]
sorry, which commit? The last one here seems to be on the Jan 20, 2017... 

Thanks a lot,
Michele

**Comment by jrupesh** [comment]
Sorry mdima,
Missed to push to master branch. The latest one is available now. (Also in 3.0.0 branch)

**Comment by mdima** [comment]
Hi jrupesh, thanks a lot! I downloaded the latest version, installed, checked, everything seems to work, thanks a lot!!

Michele

**Comment by kelnmaari** [comment]
Hi, some problem with 3.3.3.stable
Used latest master version

`Started GET "/issues/18" for 10.10.10.10 at 2018-01-12 12:09:31 +0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"18"}
  Current user: user (id=68)
  Rendered issues/_action_menu.html.erb (4.8ms)
  Rendered plugins/event_notifications/app/views/issues/show.html.erb within layouts/base (126.1ms)
Completed 500 Internal Server Error in 211ms (ActiveRecord: 39.0ms)

ActionView::Template::Error (undefined method `render_half_width_custom_fields_rows' for #<#<Class:0x007f86a71cf2e8>:0x007f86a7934e70>):
    71:       rows.right l(:label_spent_time), issue_spent_hours_details(@issue), :class => 'spent-time'
    72:     end
    73: end %>
    74: <%= render_half_width_custom_fields_rows(@issue) %>
    75: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    76: </div>
    77: 
  plugins/event_notifications/app/views/issues/show.html.erb:74:in `_plugins_event_notifications_app_views_issues_show_html_erb___1141007316000365674_70108149732940'
  app/controllers/issues_controller.rb:122:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:119:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

![screenshot_20180112_120911](https://user-images.githubusercontent.com/34859937/34867568-a7f9201c-f791-11e7-8bcd-fb49a8f229d7.png)

**Comment by jrupesh** [comment]
@kelnmaari 
I would suggest to upgrade Redmine to the latest version.
Thanks.

**Comment by kelnmaari** [comment]
After upgrade we have some errors
![screenshot_20180112_170406](https://user-images.githubusercontent.com/34859937/34878276-ae1637b8-f7ba-11e7-884d-c6314596ba3c.png)
![screenshot_20180112_170528](https://user-images.githubusercontent.com/34859937/34878297-be20579c-f7ba-11e7-9ec5-92067d44338d.png)

**Comment by jrupesh** [comment]
This is specific to localization. 
do you want to provide the translation in en-GB?
