### ISSUE TITLE
undefined method `project_issue_time_entries_path'

### ISSUE THREAD

**Issue by higuita** [jrupesh/event_notifications#11]
Using redmine 2.6 i get this with event_notifications:

ActionView::Template::Error (undefined method `project_issue_time_entries_path' for #<#$
    61:     end
    62:   end
    63:   if User.current.allowed_to?(:view_time_entries, @project)
    64:     rows.right l(:label_spent_time), (@issue.total_spent_hours > 0 ? link_to(l_$
    65:   end
    66: end %>
    67: <%= render_custom_fields_rows(@issue) %>
  app/helpers/issues_helper.rb:158:in`issue_fields_rows'
  app/controllers/issues_controller.rb:128:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:125:in`show'

Any idea how to fix this?

**Comment by ZaLiTHkA** [comment]
Apologies for resurrecting an old issue, but I'm getting this same error with Redmine 2.6.6 using the `2.0.0` branch. I can't go to Redmine 3 just yet because of other required plugins, but the "fix" you're referring to here doesn't seem to be in the `2.0.0` branch and you haven't referenced it from this issue..

@jrupesh, could you perhaps direct me to the changes you made to fix this please? It was fine in Redmine 2.5.2, only started giving me trouble after updating to 2.6.6.

**Comment by jrupesh** [comment]
Good to hear @ZaLiTHkA
