### ISSUE TITLE
Doesn't work with redmine 2.5.2.stable.13333

### ISSUE THREAD

**Issue by Aleksyy** [jrupesh/event_notifications#7]
Completed 500 Internal Server Error in 34.3ms

ActionView::Template::Error (undefined method `events' for #Member:0x0000000817cde0):
    27:              bool_val,
    28:              html_opts
    29:              ) + ' ' + h(project.name)
    30:         ) +  render_project_events_lists(project, bool_val)
